/* 
 * FileName:    TimesheetBusinessLogic.cs
 * Author:      Peter Monus
 */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using TimesheetDataAccess;

namespace TimesheetBusiness
{
    public class TimesheetBusinessLogic
    {
        TimesheetDA TDA = new TimesheetDA();

        /// <summary>AddNewTimesheet
        /// <para>
        /// Input: Foreman, WeekEnding
        /// Output: Adds new timesheet
        /// Return: Timesheet ID of new timesheet
        /// </para>
        /// </summary>
        public int AddNewTimesheet(string Foreman, DateTime WeekEnding)
        {
            int TimesheetID = TDA.AddNewTimesheet(Foreman, WeekEnding);
            return TimesheetID;
        }

        /// <summary>DeleteTimesheetEntry
        /// <para>
        /// Input: EntryID
        /// Output: Deletes specified entry
        /// Return: None
        /// </para>
        /// </summary>
        public void DeleteTimesheetEntry(string entryID)
        {            
            TDA.DeleteTimesheetEntry(entryID);
        }

        /// <summary>AddTimesheetEntry
        /// <para>
        /// Input: Timesheet ID
        /// Output: Adds new timesheet entry with only the timesheetID and a autogenerated entryID
        /// Return: None
        /// </para>
        /// </summary>
        public void AddTimesheetEntry(string timesheetID)
        {            
            TDA.AddNewTimesheetEntry(timesheetID);
        }

        /// <summary>UpdateTimesheet
        /// <para>
        /// Input: Timesheet Object
        /// Output: Updates the timesheet and entries
        /// Return: None
        /// </para>
        /// </summary>
        public void UpdateTimesheet(TimesheetObject Timesheet)
        {
            TDA.UpdateTimesheetInfo(Timesheet.timesheetID, Timesheet.submitted, Timesheet.subcontractor, Timesheet.jobsite, Timesheet.signature);

            foreach (TimesheetEntry Entry in Timesheet.Entries)
            { 
                TDA.UpdateTimesheetEntry(Entry.entryID,
                                            Entry.timesheetID,
                                            Entry.employeeID,
                                            Entry.employeeName,
                                            Entry.employeeType,
                                            Entry.hoursWednesday,
                                            Entry.hoursThursday,
                                            Entry.hoursFirday,
                                            Entry.hoursSaturday,
                                            Entry.hoursSunday,
                                            Entry.hoursMonday,
                                            Entry.hoursTuesday,
                                            Entry.comments);
            }
        }

        /// <summary>GetTimesheetList
        /// <para>
        /// Input: None/ForemanID
        /// Output: Builds a list of TimeheetListItems of all timesheets/timesheets from foreman
        /// Return: List of TimesheetListItem
        /// </para>
        /// </summary>
        public List<TimesheetListItem> GetTimesheetList()
        {
            List<TimesheetListItem> Timesheets = new List<TimesheetListItem>();

            foreach (string ts in TDA.GetTimesheetList())
            {
                TimesheetListItem sheet = new TimesheetListItem();
                string[] words = ts.Split(';');

                sheet.timesheetID = words[0].Trim();
                sheet.foremanID = words[1].Trim();
                sheet.dateEnding = words[2].Trim();
                sheet.submitted = words[3].Trim();

                Timesheets.Add(sheet);
            }

            return Timesheets;
        }

        /// <summary>GetTimesheetList
        /// <para>
        /// Input: None/ForemanID
        /// Output: Builds a list of TimeheetListItems of all timesheets/timesheets from foreman
        /// Return: List of TimesheetListItem
        /// </para>
        /// </summary>
        public List<TimesheetListItem> GetTimesheetList(string ForemanID)
        {
            List<TimesheetListItem> Timesheets = new List<TimesheetListItem>();

            foreach (string ts in TDA.GetTimesheetList(ForemanID))
            {
                TimesheetListItem sheet = new TimesheetListItem();
                string[] words = ts.Split(';');

                sheet.timesheetID = words[0].Trim();
                sheet.foremanID = words[1].Trim();
                sheet.dateEnding = words[2].Trim();
                sheet.submitted = words[3].Trim();

                Timesheets.Add(sheet);
            }

            return Timesheets;
        }

        /// <summary>GetTimesheetByID
        /// <para>
        /// Input: TimesheetID
        /// Output: Builds TimesheetObject for specified TimesheetID
        /// Return: TimesheetObject with list of TimesheetEnty objects
        /// </para>
        /// </summary>
        public TimesheetObject GetTimesheetByID(string timesheetID)
        {
            TimesheetObject TSO = new TimesheetObject();

            //Foreach string add timesheet info (There should only be one string unless two timesheets have the same ID)
            foreach (string ts in TDA.GetTimesheetDataByID(timesheetID))
            {
                string[] words = ts.Split(';');

                TSO.timesheetID = words[0].Trim();
                TSO.foremanID = words[1].Trim();
                TSO.submitted = words[2].Trim();
                TSO.weekEnding = words[3].Trim();
                TSO.jobsite = words[4].Trim();
                TSO.subcontractor = words[5].Trim();
                TSO.signature = words[6].Trim();                                
            }

            //Foreach string add Timesheet Entry
            foreach (string ts in TDA.GetTimesheetEntriesByID(timesheetID))
            {
                string[] words = ts.Split(';');

                TimesheetEntry TSE = new TimesheetEntry();

                TSE.entryID = words[0].Trim();
                TSE.timesheetID = words[1].Trim();
                TSE.employeeID = words[2].Trim();
                TSE.employeeName = words[3].Trim();
                TSE.employeeType = words[4].Trim();
                TSE.hoursWednesday = words[5].Trim();
                TSE.hoursThursday = words[6].Trim();
                TSE.hoursFirday = words[7].Trim();
                TSE.hoursSaturday = words[8].Trim();
                TSE.hoursSunday = words[9].Trim();
                TSE.hoursMonday = words[10].Trim();
                TSE.hoursTuesday = words[11].Trim();
                TSE.comments = words[12].Trim().Trim();

                TSO.Entries.Add(TSE);                
            }
            return TSO;
        }
    }
}
